export const s = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#F0F7F3',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
  },
  card: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #D1E3D9',
    borderRadius: '16px',
    padding: '40px 36px',
    width: '100%',
    maxWidth: '420px',
    boxShadow: '0 1px 4px rgba(26,107,60,0.07), 0 4px 24px rgba(26,107,60,0.06)',
  },
  brand: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '28px' },
  logoIcon: {
    width: '44px', height: '44px', backgroundColor: '#F0F7F3',
    border: '1px solid #D1E3D9', borderRadius: '10px',
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  brandName: { fontSize: '20px', fontWeight: '700', color: '#1A6B3C', letterSpacing: '-0.3px' },
  heading: { fontSize: '22px', fontWeight: '700', color: '#1A1A1A', margin: '0 0 6px', letterSpacing: '-0.3px' },
  subheading: { fontSize: '14px', color: '#5C6B63', margin: '0 0 28px' },
  form: { display: 'flex', flexDirection: 'column', gap: '16px' },
  label: { fontSize: '13px', fontWeight: '600', color: '#1A1A1A' },
  hint: { fontSize: '11px', color: '#5C6B63' },
  input: {
    width: '100%', padding: '10px 14px', fontSize: '14px', color: '#1A1A1A',
    backgroundColor: '#FFFFFF', border: '1.5px solid #D1E3D9', borderRadius: '8px',
    outline: 'none', boxSizing: 'border-box',
  },
  inputError: { borderColor: '#C0392B' },
  fieldError: { fontSize: '12px', color: '#C0392B', marginTop: '2px' },
  eyeBtn: {
    position: 'absolute', right: '12px', top: '50%', transform: 'translateY(-50%)',
    background: 'none', border: 'none', cursor: 'pointer', padding: '4px',
    display: 'flex', alignItems: 'center',
  },
  successBox: {
    display: 'flex', alignItems: 'flex-start', gap: '8px', padding: '10px 12px',
    backgroundColor: '#F0F7F3', border: '1px solid #D1E3D9', borderRadius: '8px',
    fontSize: '13px', color: '#1A6B3C',
  },
  errorBox: {
    display: 'flex', alignItems: 'flex-start', gap: '8px', padding: '10px 12px',
    backgroundColor: '#FEF2F2', border: '1px solid #FECACA', borderRadius: '8px',
    fontSize: '13px', color: '#C0392B',
  },
  btnPrimary: {
    width: '100%', padding: '11px', backgroundColor: '#1A6B3C', color: '#FFFFFF',
    fontSize: '14px', fontWeight: '600', border: 'none', borderRadius: '8px', cursor: 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center', marginTop: '4px',
  },
  btnDisabled: { backgroundColor: '#6BAF88', cursor: 'not-allowed' },
  divider: { display: 'flex', alignItems: 'center', gap: '12px', margin: '24px 0 16px' },
  dividerLine: { flex: 1, height: '1px', backgroundColor: '#D1E3D9', display: 'block' },
  dividerText: { fontSize: '12px', color: '#5C6B63', fontWeight: '500' },
  loginText: { textAlign: 'center', fontSize: '14px', color: '#5C6B63', margin: 0 },
  registerText: { textAlign: 'center', fontSize: '14px', color: '#5C6B63', margin: '0 0 12px' },
  linkBtn: {
    background: 'none', border: 'none', color: '#1A6B3C', fontWeight: '600',
    fontSize: '14px', cursor: 'pointer', padding: 0,
    textDecoration: 'underline', textUnderlineOffset: '2px',
  },
};