export const dS = {
  layoutContainer: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#F0F7F3',
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#FFFFFF',
    borderRight: '1px solid #D1E3D9',
    display: 'flex',
    flexDirection: 'column',
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 100,
    padding: '24px 0',
    boxSizing: 'border-box',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '0 24px',
    marginBottom: '32px',
  },
  logoIcon: {
    width: '36px',
    height: '36px',
    backgroundColor: '#F0F7F3',
    border: '1px solid #D1E3D9',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: {
    fontSize: '19px',
    fontWeight: '700',
    color: '#1A6B3C',
    letterSpacing: '-0.3px',
  },
  navigation: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    flex: 1,
    padding: '0 12px',
  },
  menuButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '12px 14px',
    background: 'none',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    textAlign: 'left',
    color: '#5C6B63',
    position: 'relative',
    transition: 'all 0.15s ease',
  },
  menuButtonActive: {
    backgroundColor: '#E2EFE7',
    color: '#1A6B3C',
  },
  activeIndicator: {
    position: 'absolute',
    left: '0px',
    top: '12px',
    bottom: '12px',
    width: '4px',
    backgroundColor: '#1A6B3C',
    borderRadius: '0 4px 4px 0',
  },
  icon: {
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
  },
  label: {
    fontSize: '14px',
  },
  sidebarFooter: {
    padding: '16px 24px 0 24px',
    borderTop: '1px solid #E2EFE7',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  userInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  userName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1A1A1A',
    margin: 0,
  },
  userRole: {
    fontSize: '12px',
    color: '#5C6B63',
    margin: '2px 0 0 0',
  },
  btnLogout: {
    padding: '8px 12px',
    backgroundColor: '#FEF2F2',
    color: '#C0392B',
    border: '1px solid #FECACA',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    textAlign: 'center',
    transition: 'background-color 0.15s',
  },
  mainContent: {
    flex: 1,
    marginLeft: '260px',
    minHeight: '100vh',
    boxSizing: 'border-box',
  },
  pageContainer: {
    padding: '32px',
    maxWidth: '1200px',
    margin: '0 auto',
  },

  // --- PANELS E CARD CONFIGURATIONS ---
  container: {
    padding: '24px',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    gap: '16px',
    flexWrap: 'wrap',
  },
  title: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#1A6B3C',
    margin: 0,
  },
  subtitle: {
    fontSize: '14px',
    color: '#5C6B63',
    margin: '4px 0 0 0',
  },
  btnNovo: {
    padding: '10px 16px',
    backgroundColor: '#1A6B3C',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
  },
  filterBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  filterLabel: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#2C3E35',
  },
  select: {
    padding: '8px 12px',
    border: '1px solid #D1E3D9',
    borderRadius: '8px',
    backgroundColor: '#F9FBF9',
    color: '#2C3E35',
    fontSize: '14px',
    outline: 'none',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '20px',
    marginBottom: '32px',
  },
  card: {
    padding: '20px',
    backgroundColor: '#FFFFFF',
    borderRadius: '10px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  cardLabel: {
    fontSize: '13px',
    color: '#5C6B63',
    fontWeight: '500',
  },
  cardValue: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#1A1A1A',
    margin: 0,
  },
  tableWrapper: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '14px',
  },
  thRow: {
    backgroundColor: '#F4FAF6',
  },
  th: {
    padding: '12px 16px',
    borderBottom: '2px solid #E2EFE7',
    color: '#1A6B3C',
    fontWeight: '650',
  },
  tr: {
    borderBottom: '1px solid #E2EFE7',
  },
  td: {
    padding: '14px 16px',
    color: '#2C3E35',
  },
  badge: {
    padding: '4px 8px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: '#E2EFE7',
    color: '#1A6B3C',
    display: 'inline-block',
  },
  btnVer: {
    padding: '6px 12px',
    backgroundColor: '#F4FAF6',
    color: '#1A6B3C',
    border: '1px solid #D1E3D9',
    borderRadius: '6px',
    fontWeight: '500',
    cursor: 'pointer',
    fontSize: '13px',
  },
  emptyBox: {
    textAlign: 'center',
    padding: '40px 20px',
    color: '#7A8C81',
    fontSize: '14px',
    border: '1px dashed #D1E3D9',
    borderRadius: '8px',
    backgroundColor: '#F9FBF9',
  },
  loadingText: {
    color: '#5C6B63',
    fontSize: '14px',
  }
};