apiVersion: v1
kind: Service
metadata:
  name: edualerta-api
spec:
  selector:
    app: edualerta-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edualerta-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: edualerta.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edualerta-api
                port:
                  number: 80
